name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (RuboCop)
    runs-on: ubuntu-latest
    steps:
      - name: コード取得
        uses: actions/checkout@v4
      - name: Ruby セットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: RuboCop 実行
        run: bundle exec rubocop
  test:
    name: Test (Ruby ${{ matrix.ruby }})
    runs-on: ubuntu-latest
    needs: lint  # lintが成功してから実行
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - name: コード取得
        uses: actions/checkout@v4
      - name: Ruby セットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Ruby バージョン表示
        run: ruby -v
      - name: テスト実行
        run: bundle exec ruby -Ilib:spec spec/hello_spec.rb
